### ISSUE TITLE
back: modifier le comportement de la route deck/:deckId/cards

### ISSUE THREAD

**Issue by JMJHautier** [memOria-project/memOria#27]
faire en sorte que la route deck/:deckId/cards renvoie le titre et les tags, même s'il n'y a pas de cartes dans le paquet
OU
créer deux routes séparées: 
* deck/:deckId qui renvoie toutes les infos sur un paquet, même s'il n'y a pas de cartes
* deck/:deckId/cards qui renvoie uniquement les cartes (et qui peut refuser l'envoie de paquet vide)

**Comment by JMJHautier** [comment]
priorité basse de mon coté, maintenant que j'ai pu régler #28 en utilisant user/cards plutot que deck/:deckId/cards

**Comment by vmingam** [comment]
- [ ] @S-COULIBALY Modifier la route `router.get('/deck/:id'/cards, deckController.getCardsFromDeck)` en `router.get('/deck/:id', deckController.getCardsFromDeck)`
