### ISSUE TITLE
"Key (id)=(455) is still referenced from table \"delay\"."

### ISSUE THREAD

**Issue by JMJHautier** [memOria-project/memOria#52]
J'ai ce message d'erreur (500!) quand j'essaye de supprimer certaines cartes.
J'imagine que ces cartes ont été marquées comme correctes, et qu'elles ont été ajouté au tableau "delay" en conséquence, ce qui empêche leur suppression.

Pouvez vous override ça et juste supprimer, et la carte, et sa référence dans le tableau "delay"?

**Comment by vmingam** [comment]
@JMJHautier check the PR #58
