### ISSUE TITLE
"Sanitize": vérifier que l'on est pas vulnérable à des injections de code via le formulaire des cartes

### ISSUE THREAD

**Issue by JMJHautier** [memOria-project/memOria#55]

**Comment by vmingam** [comment]
J'ai comparé 2 packages NPM: 
- [DOMPurify ](https://www.npmjs.com/package/dompurify) (orienté front) 
- [sanitize-html](https://www.npmjs.com/package/sanitize-html) orienté principalement back-end, mais fonctionne aussi pour le front (i.e. pour la preview du MD par exemple)

Côté back je vais travailler avec **sanitize-html**, @JMJHautier je te laisse choisir, si tu souhaites l'implémenter en front.

**Comment by vmingam** [comment]
Bon, j'ai implémenté un middleware `sanitazer` appelé par le `route.js`. Chaque route POST passe par le MW et toutes les propriétées de `request.body` sont passées au sanitizer et nettoyées de tous script js injectés par les formulaires du front ou directement dans les JSON vers l'API

**Comment by vmingam** [comment]
PR #76

**Comment by JMJHautier** [comment]
Bien noté Vincent. Je laisse le tiquet ouvert tant qu'il n'y a pas un sanitize en front.

**Comment by vmingam** [comment]
Désolé, je l'ai fermé par erreur. Je le réouvre pour la sécurisation du front-end
