### ISSUE TITLE
deckEditor: utiliser la route /user/cards

### ISSUE THREAD

**Issue by JMJHautier** [memOria-project/memOria#6]
https://github.com/O-clock-Uther/projet-22-memoria/issues/111

**Comment by JMJHautier** [comment]
implique aussi la création de messages d'erreurs

**Comment by JMJHautier** [comment]
pour reférence: c'était difficile. 
- user/cards ramène tous les decks et toutes les cartes, il n'y a pas de route pour un seul deck. Cela a forcé de repenser le code un petit peu
- il a fallu intégrer la route sur le profile et gérer les bugs occasionnés sur l'action de création, édition et suppression des cartes 
- l'action "CHECK_TOKEN" a créé plusieurs bugs  car elle se base sur la route user/info qui ramène toutes les infos... sauf celles des cartes, à l'intérieur de la propriété deck. Elle supprime ainsi les cartes tout juste téléchargés. Il m'a fallu du tmeps pour comprendre ça, surtout que l'action check Token est aussi déclenché via App.js à chaque premier montage de l'app.

**Comment by vmingam** [comment]
Avant de se lancer dans ce genre de refonte, on devrait échanger afin de voir si une partie du travail ne pourrait pas être fait en back en appliquant un peu de nettoyage, de clarification et cohérence.
