### ISSUE TITLE
authentification: faut-il garder le mot de passe dans le state

### ISSUE THREAD

**Issue by JMJHautier** [memOria-project/memOria#88]
solution alternative: hasher le mot de passe en front avec bcrypt?

**Comment by vmingam** [comment]
Ce n'est pas un soucis, il faut seulement s'assurer de transférer le mdp avec le protocole https à l'API

**Comment by vmingam** [comment]
Il faut simplement prévoir de vider `email` et `password` dans le state, ce qui est bien le cas selon @JMJHautier
